### ISSUE TITLE
登录流程优化

### ISSUE THREAD

**Issue by a77uu** [MaxChang3/zfnew-node#3]
## 登录并获取JESSIONID

Method: `POST`
API: `baseUrl + jwglxt/xtgl/login_slogin.html?time=${timestamp}`
Param: csrftoken(使用cheerio获取的CSRF), yhm(用户名，即学生学号), encrypted(mm) (通过RSA算法加密的密码)

Return: Set-Cookie:JESSIONID=`${JESSIONID}`; Path:/jwglxt; HttpOnly;

使用获取到的 JESSIONID 通过 Postman 测试后可正常获取数据，未通过 Nodejs 测试。

**Comment by maxchang3** [comment]
你好，感谢issue。
我没太看明白，感觉你这个流程和目前阶段是一致的？
```
this.baseUrl = baseUrl;
this.keyUrl = baseUrl + '/jwglxt/xtgl/login_getPublicKey.html';
this.loginUrl = baseUrl + '/jwglxt/xtgl/login_slogin.html';
```
首先你API那就是我这对应的loginUrl了，
那么要加密密码的话，首先就要访问keyUrl获取modulus、exponent。
那么对他发送csrftoken，就需要先访问一次loginUrl获取这玩意。
最后组合参数再发送给loginUrl了。
也就此现阶段本项目的登录流程：
获取加密密码（访问keyUrl，进行加密）=》拼凑登录参数（访问loginUrl，获取csrftoken）=》发送登录请求（访问loginUrl）
实际上和你所提的方式是一致的？
另：
没通过测试，是否和cookie有关呢，这边测试的时候手动延续cookie无用，最后打开的request的jar，才生效的。

**Comment by a77uu** [comment]
如果每次都需要Init的话，每次请求接口都得重新登录，这系统的崩溃概率你懂的 😂

**Comment by MaxChang3** [comment]
> 如果每次都需要Init的话，每次请求接口都得重新登录，这系统的崩溃概率你懂的 😂

我明白你的意思了，你的意思是使用固定的crsf和modulus、exponent所加密的密码？
我下午尝试一下。

**Comment by maxchang3** [comment]
> 如果每次都需要Init的话，每次请求接口都得重新登录，这系统的崩溃概率你懂的 😂

你的意思是保存一次登录的结果作为缓存在后期的时候直接调用？||
以及使用固定的csrf与 modulus、exponent加密的密码？

**Comment by a77uu** [comment]
> > 如果每次都需要Init的话，每次请求接口都得重新登录，这系统的崩溃概率你懂的 😂
> 
> 
> 
> 你的意思是保存一次登录的结果作为缓存在后期的时候直接调用？||
> 
> 以及使用固定的csrf与 modulus、exponent加密的密码？

可以保存JESSIONID来请求API，没必要每次都需要重新登录。如果 `statusCode == 901` 时，说明JESSIONID已失效（过期），可以在此时再重新登录。

**Comment by maxchang3** [comment]
> > > 如果每次都需要Init的话，每次请求接口都得重新登录，这系统的崩溃概率你懂的 😂
> > 
> > 
> > 你的意思是保存一次登录的结果作为缓存在后期的时候直接调用？||
> > 以及使用固定的csrf与 modulus、exponent加密的密码？
> 
> 可以保存JESSIONID来请求API，没必要每次都需要重新登录。如果 `statusCode == 901` 时，说明JESSIONID已失效（过期），可以在此时再重新登录。

了解，今天有时间的话我会增添此功能并作为一个选项，因为我需要的场景下保存JESSIONID会有一定风险。

**Comment by a77uu** [comment]
> > > > 如果每次都需要Init的话，每次请求接口都得重新登录，这系统的崩溃概率你懂的 😂
> 
> > > 
> 
> > > 
> 
> > > 你的意思是保存一次登录的结果作为缓存在后期的时候直接调用？||
> 
> > > 以及使用固定的csrf与 modulus、exponent加密的密码？
> 
> > 
> 
> > 可以保存JESSIONID来请求API，没必要每次都需要重新登录。如果 `statusCode == 901` 时，说明JESSIONID已失效（过期），可以在此时再重新登录。
> 
> 
> 
> 了解，今天有时间的话我会增添此功能并作为一个选项，因为我需要的场景下保存JESSIONID会有一定风险。

可以用jsonwebtoken生成一个 Token 返回，之后再使用它解析出来？

**Comment by maxchang3** [comment]
> > > > > 如果每次都需要Init的话，每次请求接口都得重新登录，这系统的崩溃概率你懂的 😂
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 你的意思是保存一次登录的结果作为缓存在后期的时候直接调用？||
> > 
> > 
> > > > 以及使用固定的csrf与 modulus、exponent加密的密码？
> > 
> > 
> > > 
> > 
> > 
> > > 可以保存JESSIONID来请求API，没必要每次都需要重新登录。如果 `statusCode == 901` 时，说明JESSIONID已失效（过期），可以在此时再重新登录。
> > 
> > 
> > 了解，今天有时间的话我会增添此功能并作为一个选项，因为我需要的场景下保存JESSIONID会有一定风险。
> 
> 可以用jsonwebtoken生成一个 Token 返回，之后再使用它解析出来？

使用jwt的话需要客户端那边也做适配吧

**Comment by maxchang3** [comment]
@a77uu 
https://github.com/MaxChang3/zfnew-node/tree/dev-login-cache
https://github.com/MaxChang3/zfnew-node/commit/012336106711807b563e6b524bd8b411866e146d 
我提交了不完善的缓存机制分支（缺少过期删除和选项判断），想先行测试一下效果，但是经过测试上次的headers（含cookie）保存后再次调用并无法获取信息，在抓包结果中他又重新302到了登录地址orz。 不知道你有没有思路……

**Comment by a77uu** [comment]
已经在提出了 PR #4 有疑问的话欢迎继续探讨哈

**Comment by maxchang3** [comment]
> 已经在提出了 PR #4 有疑问的话欢迎继续探讨哈

好的我看下。

**Comment by maxchang3** [comment]
> 已经在提出了 PR #4 有疑问的话欢迎继续探讨哈

那个不好意思 ，看了一下你的pr，有点没太明白，你把cookie中分割后取出了JSESSIONID后返回了然后呢，，，

**Comment by maxchang3** [comment]
另外，刚刚看了下，把route参数和jsessionid组合一起请求是可以复用的。。我估计改一下就好了

**Comment by a77uu** [comment]
（监工）我很期待你“改一改”

**Comment by maxchang3** [comment]
> （监工）我很期待你“改一改”

:/  粗略改了下，有点烂但是跑起来了，已经提交。
现在的https://github.com/MaxChang3/zfnew-node/compare/dev-login-cache
经过测试在cookie过期前可以直接获取信息。

原理大概就是检测到route就先临时保存下，最后登录成功的时候把他和JSESSIONID组合起来，创建一个缓存，之后的登录检测到这个缓存文件都会自动应用此进行提交。
route这玩意可能是我的替换cookie机制写扯了导致不知道到哪一步就丢了。

暂时未增加过期检测等（我明天重写下这部分加入，之后没问题就并入master了）

**Comment by a77uu** [comment]
> > （监工）我很期待你“改一改”
> 
> 
> 
> :/  粗略改了下，有点烂但是跑起来了，已经提交。
> 
> 现在的https://github.com/MaxChang3/zfnew-node/compare/dev-login-cache
> 
> 经过测试在cookie过期前可以直接获取信息。
> 
> 
> 
> 原理大概就是检测到route就先临时保存下，最后登录成功的时候把他和JSESSIONID组合起来，创建一个缓存，之后的登录检测到这个缓存文件都会自动应用此进行提交。
> 
> route这玩意可能是我的替换cookie机制写扯了导致不知道到哪一步就丢了。
> 
> 
> 
> 暂时未增加过期检测等（我明天重写下这部分加入，之后没问题就并入master了）

真的不想存到数据库里吗？

**Comment by maxchang3** [comment]
> 真的不想存到数据库里吗？

关于数据库的话，完全可以，也有考虑。目前dev版本只是快速实现的一个demo，后续肯定要优化的，所以我快速简单写了个存入本地文件（其实就是懒和渣渣。。）
当然这算个比较小的项目，上mongodb和mysql之类的总感觉会不会有点大材小用和麻烦，并且（我不知道会不会这样，我主观的感觉）是否在规模上不去的情况下反而会影响效率呢？
如果真的采用数据库的话我可能会采取一些小型轻量的数据库吧，上述前两个重量级选手可能会在后续以此为基础的webapi之类的项目中出现。
